### PR TITLE
added font-awesome CSS so we can use their icons

### PR DESCRIPTION
**Pull request by tylervz**

### CODE REVIEW

**Comment by jglamine** [comment]
Did you test that adding icons actually works? It looks like this might reference some files in `../fonts/`

**Comment by tylervz** [comment]
I have not yet tested it. I'll do that right now. Actually I'll do that in a few hours, because math colloquium is going to start soon.

**Comment by tylervz** [comment]
It did require files in `../fonts/`. Now it works. What do you think of this size spinners? 
loading-spinners

**Comment by jglamine** [comment]
That size is great, I'd just change the placement so they are aligned with
the headings.

**Comment by tylervz** [comment]
Alright, I updated the PR. It's ready to be merged. Fixes #13.

**Pull request merged**
